In [ ]:
# necessary import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

train_data= pd.read_csv('train_data.csv')

train_data.isna().sum()
train_data = train_data.interpolate()
train_data.isnull().sum()

df_copy = train_data[['event_id','risk','time_to_tca','max_risk_estimate', 'max_risk_scaling', 'miss_distance',
                      'relative_speed', 'relative_position_r', 'relative_position_t','relative_position_n', 
                      'relative_velocity_r', 'relative_velocity_t','relative_velocity_n',
                      't_time_lastob_start', 't_time_lastob_end', 't_recommended_od_span','t_actual_od_span',
                      't_obs_available','t_obs_used', 't_residuals_accepted', 't_weighted_rms','t_rcs_estimate',
                      't_cd_area_over_mass', 't_cr_area_over_mass','t_sedr', 't_j2k_sma', 't_j2k_ecc', 't_j2k_inc',
                      't_ct_r', 't_cn_r', 't_cn_t', 't_crdot_r', 't_crdot_t', 't_crdot_n', 't_ctdot_r','t_ctdot_t',
                      't_ctdot_n', 't_ctdot_rdot', 't_cndot_r','t_cndot_t', 't_cndot_n', 't_cndot_rdot',
                      't_cndot_tdot', 'c_time_lastob_start', 'c_time_lastob_end','c_recommended_od_span',
                      'c_actual_od_span','c_obs_available', 'c_obs_used', 'c_residuals_accepted','c_weighted_rms',
                      'c_cd_area_over_mass','c_cr_area_over_mass', 'c_sedr', 'c_j2k_sma', 'c_j2k_ecc', 'c_j2k_inc',
                      'c_ct_r', 'c_cn_r', 'c_cn_t','c_crdot_r', 'c_crdot_t', 'c_crdot_n', 'c_ctdot_r', 'c_ctdot_t',
                      'c_ctdot_n','c_ctdot_rdot', 'c_cndot_r','c_cndot_t', 'c_cndot_n','c_ctdot_rdot', 'c_cndot_r',
                      'c_cndot_t', 'c_cndot_n','c_cndot_rdot', 'c_cndot_tdot', 't_span', 'c_span', 't_h_apo',
                      't_h_per', 'c_h_apo', 'c_h_per', 'geocentric_latitude', 'azimuth', 'mahalanobis_distance',
                      't_sigma_r', 'c_sigma_r', 't_sigma_t', 'c_sigma_t', 't_sigma_n','c_sigma_n', 't_sigma_rdot',
                      'c_sigma_rdot', 't_sigma_tdot', 'c_sigma_tdot', 't_sigma_ndot',
                      'c_sigma_ndot', 'F10', 'F3M', 'SSN', 'AP']]

X = df_copy.drop(['risk'], axis=1)
y = df_copy.risk

# Preprocess the dataset and divide into train and test
sc = StandardScaler()
X = sc.fit_transform(X)
le = LabelEncoder()
y = le.fit_transform(y)
X_train, X_test,\
    y_train, y_test = train_test_split(X, y,
                                       test_size=0.2)

# apply Linear Discriminant Analysis
lda = LinearDiscriminantAnalysis(n_components=40) #this is the line i was changeing i was changing (n_components)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

 # create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train,y_train)
predR = regressor.predict(X_test)
rmseR = np.sqrt(mean_squared_error(y_test, predR))
mseR=mean_squared_error(y_test,predR)
maeR=mean_absolute_error(y_test,predR)
r2R=r2_score(y_test,predR)
result1=[rmseR,mseR,maeR,r2R]
df_R = pd.DataFrame({'RandomForestRegressor':result1},index=['RMSE:','MSE:','MAE:','R2-score:'])
df_R

In [7]:
# necessary import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

train_data= pd.read_csv('train_data.csv')

train_data.isna().sum()
train_data = train_data.interpolate()
train_data.isnull().sum()

df_copy = train_data[['event_id','risk','time_to_tca','max_risk_estimate', 'max_risk_scaling', 'miss_distance',
                      'relative_speed', 'relative_position_r', 'relative_position_t','relative_position_n', 
                      'relative_velocity_r', 'relative_velocity_t','relative_velocity_n',
                      't_time_lastob_start', 't_time_lastob_end', 't_recommended_od_span','t_actual_od_span',
                      't_obs_available','t_obs_used', 't_residuals_accepted', 't_weighted_rms','t_rcs_estimate',
                      't_cd_area_over_mass', 't_cr_area_over_mass','t_sedr', 't_j2k_sma', 't_j2k_ecc', 't_j2k_inc',
                      't_ct_r', 't_cn_r', 't_cn_t', 't_crdot_r', 't_crdot_t', 't_crdot_n', 't_ctdot_r','t_ctdot_t',
                      't_ctdot_n', 't_ctdot_rdot', 't_cndot_r','t_cndot_t', 't_cndot_n', 't_cndot_rdot',
                      't_cndot_tdot', 'c_time_lastob_start', 'c_time_lastob_end','c_recommended_od_span',
                      'c_actual_od_span','c_obs_available', 'c_obs_used', 'c_residuals_accepted','c_weighted_rms',
                      'c_cd_area_over_mass','c_cr_area_over_mass', 'c_sedr', 'c_j2k_sma', 'c_j2k_ecc', 'c_j2k_inc',
                      'c_ct_r', 'c_cn_r', 'c_cn_t','c_crdot_r', 'c_crdot_t', 'c_crdot_n', 'c_ctdot_r', 'c_ctdot_t',
                      'c_ctdot_n','c_ctdot_rdot', 'c_cndot_r','c_cndot_t', 'c_cndot_n','c_ctdot_rdot', 'c_cndot_r',
                      'c_cndot_t', 'c_cndot_n','c_cndot_rdot', 'c_cndot_tdot', 't_span', 'c_span', 't_h_apo',
                      't_h_per', 'c_h_apo', 'c_h_per', 'geocentric_latitude', 'azimuth', 'mahalanobis_distance',
                      't_sigma_r', 'c_sigma_r', 't_sigma_t', 'c_sigma_t', 't_sigma_n','c_sigma_n', 't_sigma_rdot',
                      'c_sigma_rdot', 't_sigma_tdot', 'c_sigma_tdot', 't_sigma_ndot',
                      'c_sigma_ndot', 'F10', 'F3M', 'SSN', 'AP']]

X = df_copy.drop(['risk'], axis=1)
y = df_copy.risk

# Preprocess the dataset and divide into train and test
sc = StandardScaler()
X = sc.fit_transform(X)
le = LabelEncoder()
y = le.fit_transform(y)
X_train, X_test,\
    y_train, y_test = train_test_split(X, y,
                                       test_size=0.2)

# apply Linear Discriminant Analysis
lda = LinearDiscriminantAnalysis(n_components=50)#this is the line i was changeing i was changing (n_components)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

 # create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train,y_train)
predR = regressor.predict(X_test)
rmseR = np.sqrt(mean_squared_error(y_test, predR))
mseR=mean_squared_error(y_test,predR)
maeR=mean_absolute_error(y_test,predR)
r2R=r2_score(y_test,predR)
result1=[rmseR,mseR,maeR,r2R]
df_R = pd.DataFrame({'RandomForestRegressor':result1},index=['RMSE:','MSE:','MAE:','R2-score:'])
df_R

           RandomForestRegressor
RMSE:               9.520999e+03
MSE:                9.064942e+07
MAE:                6.351541e+03
R2-score:           7.921123e-01

In [8]:
# necessary import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

train_data= pd.read_csv('train_data.csv')

train_data.isna().sum()
train_data = train_data.interpolate()
train_data.isnull().sum()

df_copy = train_data[['event_id','risk','time_to_tca','max_risk_estimate', 'max_risk_scaling', 'miss_distance',
                      'relative_speed', 'relative_position_r', 'relative_position_t','relative_position_n', 
                      'relative_velocity_r', 'relative_velocity_t','relative_velocity_n',
                      't_time_lastob_start', 't_time_lastob_end', 't_recommended_od_span','t_actual_od_span',
                      't_obs_available','t_obs_used', 't_residuals_accepted', 't_weighted_rms','t_rcs_estimate',
                      't_cd_area_over_mass', 't_cr_area_over_mass','t_sedr', 't_j2k_sma', 't_j2k_ecc', 't_j2k_inc',
                      't_ct_r', 't_cn_r', 't_cn_t', 't_crdot_r', 't_crdot_t', 't_crdot_n', 't_ctdot_r','t_ctdot_t',
                      't_ctdot_n', 't_ctdot_rdot', 't_cndot_r','t_cndot_t', 't_cndot_n', 't_cndot_rdot',
                      't_cndot_tdot', 'c_time_lastob_start', 'c_time_lastob_end','c_recommended_od_span',
                      'c_actual_od_span','c_obs_available', 'c_obs_used', 'c_residuals_accepted','c_weighted_rms',
                      'c_cd_area_over_mass','c_cr_area_over_mass', 'c_sedr', 'c_j2k_sma', 'c_j2k_ecc', 'c_j2k_inc',
                      'c_ct_r', 'c_cn_r', 'c_cn_t','c_crdot_r', 'c_crdot_t', 'c_crdot_n', 'c_ctdot_r', 'c_ctdot_t',
                      'c_ctdot_n','c_ctdot_rdot', 'c_cndot_r','c_cndot_t', 'c_cndot_n','c_ctdot_rdot', 'c_cndot_r',
                      'c_cndot_t', 'c_cndot_n','c_cndot_rdot', 'c_cndot_tdot', 't_span', 'c_span', 't_h_apo',
                      't_h_per', 'c_h_apo', 'c_h_per', 'geocentric_latitude', 'azimuth', 'mahalanobis_distance',
                      't_sigma_r', 'c_sigma_r', 't_sigma_t', 'c_sigma_t', 't_sigma_n','c_sigma_n', 't_sigma_rdot',
                      'c_sigma_rdot', 't_sigma_tdot', 'c_sigma_tdot', 't_sigma_ndot',
                      'c_sigma_ndot', 'F10', 'F3M', 'SSN', 'AP']]

X = df_copy.drop(['risk'], axis=1)
y = df_copy.risk

# Preprocess the dataset and divide into train and test
sc = StandardScaler()
X = sc.fit_transform(X)
le = LabelEncoder()
y = le.fit_transform(y)
X_train, X_test,\
    y_train, y_test = train_test_split(X, y,
                                       test_size=0.2)

# apply Linear Discriminant Analysis
lda = LinearDiscriminantAnalysis(n_components=60)#this is the line i was changeing i was changing (n_components)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

 # create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train,y_train)
predR = regressor.predict(X_test)
rmseR = np.sqrt(mean_squared_error(y_test, predR))
mseR=mean_squared_error(y_test,predR)
maeR=mean_absolute_error(y_test,predR)
r2R=r2_score(y_test,predR)
result1=[rmseR,mseR,maeR,r2R]
df_R = pd.DataFrame({'RandomForestRegressor':result1},index=['RMSE:','MSE:','MAE:','R2-score:'])
df_R

           RandomForestRegressor
RMSE:               9.175390e+03
MSE:                8.418778e+07
MAE:                6.086618e+03
R2-score:           8.065594e-01

In [9]:
# necessary import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

train_data= pd.read_csv('train_data.csv')

train_data.isna().sum()
train_data = train_data.interpolate()
train_data.isnull().sum()

df_copy = train_data[['event_id','risk','time_to_tca','max_risk_estimate', 'max_risk_scaling', 'miss_distance',
                      'relative_speed', 'relative_position_r', 'relative_position_t','relative_position_n', 
                      'relative_velocity_r', 'relative_velocity_t','relative_velocity_n',
                      't_time_lastob_start', 't_time_lastob_end', 't_recommended_od_span','t_actual_od_span',
                      't_obs_available','t_obs_used', 't_residuals_accepted', 't_weighted_rms','t_rcs_estimate',
                      't_cd_area_over_mass', 't_cr_area_over_mass','t_sedr', 't_j2k_sma', 't_j2k_ecc', 't_j2k_inc',
                      't_ct_r', 't_cn_r', 't_cn_t', 't_crdot_r', 't_crdot_t', 't_crdot_n', 't_ctdot_r','t_ctdot_t',
                      't_ctdot_n', 't_ctdot_rdot', 't_cndot_r','t_cndot_t', 't_cndot_n', 't_cndot_rdot',
                      't_cndot_tdot', 'c_time_lastob_start', 'c_time_lastob_end','c_recommended_od_span',
                      'c_actual_od_span','c_obs_available', 'c_obs_used', 'c_residuals_accepted','c_weighted_rms',
                      'c_cd_area_over_mass','c_cr_area_over_mass', 'c_sedr', 'c_j2k_sma', 'c_j2k_ecc', 'c_j2k_inc',
                      'c_ct_r', 'c_cn_r', 'c_cn_t','c_crdot_r', 'c_crdot_t', 'c_crdot_n', 'c_ctdot_r', 'c_ctdot_t',
                      'c_ctdot_n','c_ctdot_rdot', 'c_cndot_r','c_cndot_t', 'c_cndot_n','c_ctdot_rdot', 'c_cndot_r',
                      'c_cndot_t', 'c_cndot_n','c_cndot_rdot', 'c_cndot_tdot', 't_span', 'c_span', 't_h_apo',
                      't_h_per', 'c_h_apo', 'c_h_per', 'geocentric_latitude', 'azimuth', 'mahalanobis_distance',
                      't_sigma_r', 'c_sigma_r', 't_sigma_t', 'c_sigma_t', 't_sigma_n','c_sigma_n', 't_sigma_rdot',
                      'c_sigma_rdot', 't_sigma_tdot', 'c_sigma_tdot', 't_sigma_ndot',
                      'c_sigma_ndot', 'F10', 'F3M', 'SSN', 'AP']]

X = df_copy.drop(['risk'], axis=1)
y = df_copy.risk

# Preprocess the dataset and divide into train and test
sc = StandardScaler()
X = sc.fit_transform(X)
le = LabelEncoder()
y = le.fit_transform(y)
X_train, X_test,\
    y_train, y_test = train_test_split(X, y,
                                       test_size=0.2)

# apply Linear Discriminant Analysis
lda = LinearDiscriminantAnalysis(n_components=70)#this is the line i was changeing i was changing (n_components)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

 # create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train,y_train)
predR = regressor.predict(X_test)
rmseR = np.sqrt(mean_squared_error(y_test, predR))
mseR=mean_squared_error(y_test,predR)
maeR=mean_absolute_error(y_test,predR)
r2R=r2_score(y_test,predR)
result1=[rmseR,mseR,maeR,r2R]
df_R = pd.DataFrame({'RandomForestRegressor':result1},index=['RMSE:','MSE:','MAE:','R2-score:'])
df_R

           RandomForestRegressor
RMSE:               9.455871e+03
MSE:                8.941350e+07
MAE:                6.355836e+03
R2-score:           7.936193e-01