In [18]:
''''''this is to use the specified features with raandom forest

SyntaxError: invalid syntax (<ipython-input-18-de393d07ccf2>, line 1)

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [3]:
train_data= pd.read_csv('train_data.csv')
train_data

,event_id,time_to_tca,mission_id,risk,max_risk_estimate,max_risk_scaling,miss_distance,relative_speed,relative_position_r,relative_position_t,...,t_sigma_rdot,c_sigma_rdot,t_sigma_tdot,c_sigma_tdot,t_sigma_ndot,c_sigma_ndot,F10,F3M,SSN,AP
0,0,1.566798,5,-10.204955,-7.834756,8.602101,14923.0,13792.0,453.8,5976.6,...,0.147350,58.272095,0.004092,0.165044,0.002987,0.386462,89.0,83.0,42.0,11.0
1,0,1.207494,5,-10.355758,-7.848937,8.956374,14544.0,13792.0,474.3,5821.2,...,0.059672,57.966413,0.003753,0.164383,0.002933,0.386393,89.0,83.0,42.0,11.0
2,0,0.952193,5,-10.345631,-7.847406,8.932195,14475.0,13792.0,474.6,5796.2,...,0.039258,57.907599,0.003576,0.164352,0.002967,0.386381,89.0,83.0,42.0,11.0
3,0,0.579669,5,-10.337809,-7.845880,8.913444,14579.0,13792.0,472.7,5838.9,...,0.022066,57.993905,0.003298,0.164309,0.002918,0.386400,89.0,83.0,40.0,14.0
4,0,0.257806,5,-10.391260,-7.852942,9.036838,14510.0,13792.0,478.7,5811.1,...,0.015075,57.946717,0.003670,0.164172,0.003220,0.386388,89.0,83.0,40.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162629,13153,3.029751,1,-7.108630,-5.142668,7.561579,2307.0,14976.0,-472.1,-159.9,...,0.071060,48.480202,0.011479,0.145746,0.002764,0.231577,81.0,84.0,48.0,18.0
162630,13153,2.799253,1,-7.070070,-5.137869,7.471857,2254.0,14976.0,-469.7,-163.3,...,0.063959,48.565132,0.009935,0.145729,0.002678,0.231583,78.0,84.0,49.0,19.0
162631,13153,2.385399,1,-7.066209,-5.137034,7.463470,2259.0,14976.0,-469.3,-158.8,...,0.059657,48.547317,0.009491,0.145745,0.002632,0.231582,78.0,84.0,49.0,19.0
162632,13153,2.043339,1,-7.028307,-5.131297,7.378397,2257.0,14976.0,-465.2,-160.3,...,0.039351,48.540602,0.002612,0.145734,0.002631,0.231583,78.0,84.0,49.0,19.0
162633,13153,1.618095,1,-7.172372,-5.152181,7.705750,2185.0,14976.0,-479.6,-156.0,...,0.047452,48.673155,0.009494,0.145716,0.002693,0.231592,78.0,84.0,48.0,10.0

In [4]:
train_data.isna().sum()

event_id                0
time_to_tca             0
mission_id              0
risk                    0
max_risk_estimate       0
                     ...
c_sigma_ndot         9241
F10                  6822
F3M                  6822
SSN                  6822
AP                   6822
Length: 103, dtype: int64

In [5]:
train_data = train_data.interpolate()
train_data.isnull().sum()

event_id             0
time_to_tca          0
mission_id           0
risk                 0
max_risk_estimate    0
                    ..
c_sigma_ndot         0
F10                  0
F3M                  0
SSN                  0
AP                   0
Length: 103, dtype: int64

In [6]:
# normal correlation
df_copy=train_data[['risk', 'time_to_tca', 'c_time_lastob_end', 'c_time_lastob_start', 'max_risk_estimate', 'c_ctdot_r', 
                    'c_recommended_od_span', 'c_actual_od_span', 'c_cr_area_over_mass', 't_cn_r', 'c_cd_area_over_mass',
                    'c_weighted_rms', 'c_cndot_n', 't_weighted_rms', 't_j2k_inc', 't_ctdot_r', 't_cndot_n', 't_h_apo', 'c_sigma_t',
                    'c_sigma_r', 'c_sigma_n', 'relative_velocity_t', 't_j2k_sma', 't_j2k_ecc','t_sigma_t', 't_sigma_r',
                    't_sigma_n', 't_cd_area_over_mass', 'c_sigma_rdot','t_recommended_od_span', 't_h_per', 't_sigma_rdot',
                    't_sigma_tdot', 't_sigma_ndot', 'c_sigma_tdot', 'c_sigma_ndot', 'c_j2k_ecc', 't_ctdot_t', 'c_sedr',
                    't_actual_od_span', 'c_h_per', 't_crdot_r', 'c_j2k_sma', 'c_h_apo', 'c_ct_r', 'mission_id', 'c_crdot_t',
                    'relative_position_r', 'c_ctdot_t', 'c_cn_r', 'c_crdot_n', 'c_cndot_rdot', 'c_cndot_r', 
                    't_cndot_r', 't_cndot_t', 't_crdot_n']]
df_copy

,risk,time_to_tca,c_time_lastob_end,c_time_lastob_start,max_risk_estimate,c_ctdot_r,c_recommended_od_span,c_actual_od_span,c_cr_area_over_mass,t_cn_r,...,c_crdot_t,relative_position_r,c_ctdot_t,c_cn_r,c_crdot_n,c_cndot_rdot,c_cndot_r,t_cndot_r,t_cndot_t,t_crdot_n
0,-10.204955,1.566798,2.0,180.0,-7.834756,-0.732954,15.85,15.85,0.126607,0.292258,...,-0.999998,453.8,0.220006,0.473976,0.003565,-0.196908,0.249855,0.170737,-0.001551,-0.038498
1,-10.355758,1.207494,2.0,180.0,-7.848937,-0.728759,15.85,15.85,0.126607,0.297366,...,-0.999998,474.3,0.202595,0.482754,0.004574,-0.196008,0.258964,0.179696,0.001552,-0.052511
2,-10.345631,0.952193,2.0,180.0,-7.847406,-0.729083,15.85,15.85,0.126607,0.305189,...,-0.999998,474.6,0.201698,0.483828,0.004738,-0.195849,0.260092,0.123760,0.019630,-0.034287
3,-10.337809,0.579669,2.0,180.0,-7.845880,-0.728092,15.85,15.85,0.126607,0.423647,...,-0.999998,472.7,0.200534,0.483678,0.004755,-0.196097,0.259681,0.228051,0.039163,-0.149998
4,-10.391260,0.257806,2.0,180.0,-7.852942,-0.727257,15.85,15.85,0.126607,0.406002,...,-0.999998,478.7,0.196662,0.485794,0.005077,-0.195947,0.261753,0.223469,0.118674,-0.243006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162629,-7.108630,3.029751,2.0,180.0,-5.142668,-0.664416,28.89,28.89,0.271941,-0.034608,...,-0.999999,-472.1,-0.272000,-0.717118,0.031831,-0.060522,0.642434,-0.062345,-0.097198,0.055494
162630,-7.070070,2.799253,2.0,180.0,-5.137869,-0.663148,28.89,28.89,0.271941,0.123080,...,-0.999999,-469.7,-0.271754,-0.716144,0.031870,-0.060633,0.641449,0.048059,-0.007804,-0.049440
162631,-7.066209,2.385399,2.0,180.0,-5.137034,-0.663521,28.89,28.89,0.271941,0.055617,...,-0.999999,-469.3,-0.272079,-0.716553,0.031871,-0.060608,0.641860,-0.003326,-0.029615,-0.032178
162632,-7.028307,2.043339,2.0,180.0,-5.131297,-0.663776,28.89,28.89,0.271941,0.251362,...,-0.999999,-465.2,-0.271822,-0.716592,0.031868,-0.060597,0.641902,0.015642,-0.026169,-0.049582
162633,-7.172372,1.618095,2.0,180.0,-5.152181,-0.661655,28.89,28.89,0.271941,-0.002622,...,-0.999999,-479.6,-0.271600,-0.715069,0.031910,-0.060763,0.640355,0.019767,-0.041085,0.012904

In [7]:
from sklearn.model_selection import train_test_split

X = df_copy.drop(['risk'], axis=1)
y = df_copy.risk

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

In [8]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

 # create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train,y_train)
predR = regressor.predict(X_test)
rmseR = np.sqrt(mean_squared_error(y_test, predR))
mseR=mean_squared_error(y_test,predR)
maeR=mean_absolute_error(y_test,predR)
r2R=r2_score(y_test,predR)
result1=[rmseR,mseR,maeR,r2R]
df_R = pd.DataFrame({'RandomForestRegressor':result1},index=['RMSE:','MSE:','MAE:','R2-score:'])
df_R

           RandomForestRegressor
RMSE:                   2.027524
MSE:                    4.110854
MAE:                    1.015569
R2-score:               0.958956

In [9]:
import pickle 

filename = 'random_model1.sav'
pickle.dump(regressor, open(filename, 'wb'))

In [10]:
#with correlation of spearman

In [11]:
#  correlation spearman
df_copy=train_data[['risk', 'time_to_tca', 'c_time_lastob_end', 'max_risk_estimate', 'c_ctdot_r', 'c_recommended_od_span',
                    'c_actual_od_span', 'c_cr_area_over_mass', 't_cn_r', 'c_cd_area_over_mass', 'c_weighted_rms', 'c_cndot_n',
                    't_ctdot_r', 'c_sigma_t', 'c_sigma_r', 'c_sigma_n', 't_sigma_t', 't_sigma_r', 'c_sigma_rdot', 't_sigma_rdot',
                    't_sigma_tdot', 'c_sigma_tdot', 'c_sigma_ndot', 'c_sedr', 'c_crdot_t', 't_crdot_t', 'max_risk_scaling',
                    't_ctdot_n', 't_span', 'c_span', 'c_obs_available', 'miss_distance', 'c_obs_used', 'mahalanobis_distance']]

df_copy

,risk,time_to_tca,c_time_lastob_end,max_risk_estimate,c_ctdot_r,c_recommended_od_span,c_actual_od_span,c_cr_area_over_mass,t_cn_r,c_cd_area_over_mass,...,c_crdot_t,t_crdot_t,max_risk_scaling,t_ctdot_n,t_span,c_span,c_obs_available,miss_distance,c_obs_used,mahalanobis_distance
0,-10.204955,1.566798,2.0,-7.834756,-0.732954,15.85,15.85,0.126607,0.292258,0.348701,...,-0.999998,-0.999674,8.602101,-0.316493,1.0,2.0,15.0,14923.0,15.0,129.430951
1,-10.355758,1.207494,2.0,-7.848937,-0.728759,15.85,15.85,0.126607,0.297366,0.348701,...,-0.999998,-0.998192,8.956374,-0.302333,1.0,2.0,15.0,14544.0,15.0,271.540424
2,-10.345631,0.952193,2.0,-7.847406,-0.729083,15.85,15.85,0.126607,0.305189,0.348701,...,-0.999998,-0.996235,8.932195,-0.308501,1.0,2.0,15.0,14475.0,15.0,347.899292
3,-10.337809,0.579669,2.0,-7.845880,-0.728092,15.85,15.85,0.126607,0.423647,0.348701,...,-0.999998,-0.990913,8.913444,-0.427166,1.0,2.0,15.0,14579.0,15.0,435.376626
4,-10.391260,0.257806,2.0,-7.852942,-0.727257,15.85,15.85,0.126607,0.406002,0.348701,...,-0.999998,-0.983144,9.036838,-0.405723,1.0,2.0,15.0,14510.0,15.0,469.178802
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162629,-7.108630,3.029751,2.0,-5.142668,-0.664416,28.89,28.89,0.271941,-0.034608,1.001898,...,-0.999999,-0.990310,7.561579,0.034441,21.0,2.0,17.0,2307.0,15.0,45.789081
162630,-7.070070,2.799253,2.0,-5.137869,-0.663148,28.89,28.89,0.271941,0.123080,1.001898,...,-0.999999,-0.990605,7.471857,-0.123415,21.0,2.0,17.0,2254.0,15.0,44.748673
162631,-7.066209,2.385399,2.0,-5.137034,-0.663521,28.89,28.89,0.271941,0.055617,1.001898,...,-0.999999,-0.991510,7.463470,-0.056051,21.0,2.0,17.0,2259.0,15.0,45.020671
162632,-7.028307,2.043339,2.0,-5.131297,-0.663776,28.89,28.89,0.271941,0.251362,1.001898,...,-0.999999,-0.998222,7.378397,-0.252490,21.0,2.0,17.0,2257.0,15.0,45.262300
162633,-7.172372,1.618095,2.0,-5.152181,-0.661655,28.89,28.89,0.271941,-0.002622,1.001898,...,-0.999999,-0.993624,7.705750,0.002176,21.0,2.0,17.0,2185.0,15.0,43.445526

In [12]:
from sklearn.model_selection import train_test_split

X = df_copy.drop(['risk'], axis=1)
y = df_copy.risk

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

In [13]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

 # create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train,y_train)
predR = regressor.predict(X_test)
rmseR = np.sqrt(mean_squared_error(y_test, predR))
mseR=mean_squared_error(y_test,predR)
maeR=mean_absolute_error(y_test,predR)
r2R=r2_score(y_test,predR)
result1=[rmseR,mseR,maeR,r2R]
df_R = pd.DataFrame({'RandomForestRegressor':result1},index=['RMSE:','MSE:','MAE:','R2-score:'])
df_R

           RandomForestRegressor
RMSE:                   0.099038
MSE:                    0.009808
MAE:                    0.023032
R2-score:               0.999902

In [14]:
import pickle 

filename = 'random_model2.sav'
pickle.dump(regressor, open(filename, 'wb'))

In [15]:
# to import the saved model

In [16]:
# import packages 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression 
from sklearn import metrics 
import pickle 

# save the model 
filename = 'random_model2.sav'
# load the model 
load_model = pickle.load(open(filename, 'rb'))

train_data= pd.read_csv('train_data.csv')

train_data.isna().sum()

train_data = train_data.interpolate()
train_data.isnull().sum()

df_copy=train_data[['risk', 'time_to_tca', 'c_time_lastob_end', 'max_risk_estimate', 'c_ctdot_r', 'c_recommended_od_span',
                    'c_actual_od_span', 'c_cr_area_over_mass', 't_cn_r', 'c_cd_area_over_mass', 'c_weighted_rms', 'c_cndot_n',
                    't_ctdot_r', 'c_sigma_t', 'c_sigma_r', 'c_sigma_n', 't_sigma_t', 't_sigma_r', 'c_sigma_rdot', 't_sigma_rdot',
                    't_sigma_tdot', 'c_sigma_tdot', 'c_sigma_ndot', 'c_sedr', 'c_crdot_t', 't_crdot_t', 'max_risk_scaling',
                    't_ctdot_n', 't_span', 'c_span', 'c_obs_available', 'miss_distance', 'c_obs_used', 'mahalanobis_distance']]


from sklearn.model_selection import train_test_split

X = df_copy.drop(['risk'], axis=1)
y = df_copy.risk


from sklearn.model_selection import train_test_split

X = df_copy.drop(['risk'], axis=1)
y = df_copy.risk

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=100)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score


predR = load_model.predict(X_test)

rmseR = np.sqrt(mean_squared_error(y_test, predR))
mseR=mean_squared_error(y_test,predR)
maeR=mean_absolute_error(y_test,predR)
r2R=r2_score(y_test,predR)
result1=[rmseR,mseR,maeR,r2R]
df_R = pd.DataFrame({'RandomForestRegressor':result1},index=['RMSE:','MSE:','MAE:','R2-score:'])
df_R

           RandomForestRegressor
RMSE:                   0.073966
MSE:                    0.005471
MAE:                    0.015798
R2-score:               0.999945